### DISCUSSION TITLE
MarkovJunior syntax proposal

### DISCUSSION THREAD

**Discussion by kaya3** [mxgmn/MarkovJunior#43] [Ideas]
I started thinking about a simpler syntax for MarkovJunior programs, because at least personally I think XML is a bit tedious to write, and a parser based on XML will silently ignore any tags or attributes it doesn't look for, which may make it harder to notice mistakes (particularly when an attribute is added to the wrong tag, or misspelled). And because designing languages is fun.

Comments and suggestions from everyone interested in MarkovJunior are appreciated! I'll illustrate the syntax with examples below, translated from the example models. I'm doing this for my own project mainly, but @mxgmn if this is something you're interested in, I'd be happy to write a parser for the official MarkovJunior project in C# once this syntax is complete and set in stone. (No worries if you don't think this would be a good idea.)

### Backtracker
```
# Generates connected cave systems with pools.

values [BRWU]

once: origin -> (R)
markov:
    one: (RB) -> (WR)
    one: (RW) -> (UR)
```

### BacktrackerCycle
```
# Generates a random cycle.

values [BRGWA]

once: origin -> (R)

markov:
    one: (RBB) -> (GGR)
    one: (RGG) -> (WAR)

once: (R) -> (W)
once: (WBW) -> (WAW)
all: (A) -> (W)
all: (BBB/BWB) -> (.../.B.)
```

### BasicBrickWall
```
values [BWO]
symmetry "x"

all: (B/.) -> (O/.)
all: (O/./.) -> (W/./.)

markov:
    all: (BW) -> (BB)
    one: (W/W/W/W/W/W/W/W) -> (./././B/./././.)

one: (OOOOOOOO/BBBBBBBB) -> (...B..../........)

markov:
    symmetry "xy" @ all: (OW) -> (.O)
    all: (OO/OB) -> (.B/..)
    one: (OOOO/BBBB/OOOO) -> (..B./..../....)
    one: (WW/BB/OB) -> (.O/../..)
```

### BasicDijkstraDungeon
```
values [BGW]

legend [BW]
let roomIn | roomOut = load "BasicDijkstraRoom.png"

once: roomIn -> roomOut
all: (W) -> (G)

markov:
    all: (GW) -> (GG)
    path {from=[W], to=[G], input=[B], output=[G], inertia=true}
    one: roomIn -> roomOut
```

### BasicSnake
```
values [BWDPGR]

once: origin -> (W)

all:
    (WBB) -> (..D)
    (DBB) -> (..D)

one: (WBD) -> (PGR)
one {limit=2}: (RBD) -> (GGR)
one {limit=15}: (D) -> (W)

markov:
    one: (RBW) -> (GGR)
    all:
        (RBD) -> (GGR)
        (PGG) -> (DBP)
```

A few notes on some of the design decisions:
- The syntax is inspired by Python, so blocks are denoted by indentation rather than delimiters, and statements are terminated by newlines instead of semicolons. I like this, but I know not everyone does. It would be possible to use `{}` for blocks if arguments like `limit=2` were written without delimiters, or with `()` delimiters (although that would make tokenization harder because it conflicts with patterns); another option would be to use keywords like `endall`, `endmarkov` etc., though I'm not a fan of this.
- The root is a sequence node, instead of a Markov node by default. This is consistent with other imperative languages, which most programmers are used to. Sequences can be nested in Markov nodes by writing `sequence:`, though this doesn't occur in the examples above.
- I chose `.` instead of `*` for wildcards; this is consistent with regexes, a bit visually clearer IMO, a bit easier to type on many keyboards, and avoids having `/*` or `*/` occur inside patterns (which can be a pain when writing patterns inside strings in another language, where those delimit comments).
- `once` is syntax sugar for `one {limit=1}`.
- I made `origin` a special pattern which matches at the centre of the grid, instead of a boolean flag. This means you can rewrite `origin` with any pattern (not just a colour in one cell), anywhere in the program. Semantically, an `origin -> ...` rule returns false if the output pattern is already present, so there is no infinite loop if it's used in a `markov` node. In principle, rules could allow other position-based input patterns (this would require some syntax for describing positions).
- The grammar can be parsed without looking more than one token ahead.

I'm also writing a parser for this syntax, for my own project, and to make sure it works from an implementer's perspective. Including type definitions, it's currently at about 530 lines of TypeScript code, and can successfully parse all of the examples above. It would be good to get feedback about the syntax before doing much more work on it, though.
